services:
  server:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
     - ./src:/app/src
     - /node_modules